stevengj/nlopt

- api/general.c
- slsqp/slsqp.c
- util/nlopt-util.h
I'm not sure how to run the standard tests, but I've tested this against our test collection in OpenMx. For context, see issue #30.
> soft feasibility constraints for slsqp

- octave/nlopt_optimize-oct.cc
This supports octave 4.0 and works at least in octave 3.8 if not earlier.
> Use octave_map

- auglag/auglag.c
Patch courtesy of @jakebiesinger.
> Fixes memory leak in auglag/auglag.c

- swig/Makefile.am
Also link with GUILE_LIBS which I forgot in previous PR.
> also link with GUILE_LIBS

- CMakeLists.txt
> Detect CXX compiler by default

- CMakeLists.txt
> Detect libm

- .travis.yml
- test/CMakeLists.txt
> Support cmake && make && ctest

- cobyla/cobyla.c
Reportedly fixes #51, patch from @dariomt
> fix compilation problem with MSVC

- bobyqa/bobyqa.c
- cobyla/cobyla.c
- luksan/pnet.c
- luksan/pssubs.c
- mma/ccsa_quadratic.c
- newuoa/newuoa.c
- praxis/praxis.c
- slsqp/slsqp.c
Every variables that yields a -Wmaybe-uninitialized gcc warning are set to 0
Fixes #133
> Fix all uninitialized variable warnings

- CMakeLists.txt
- octave/CMakeLists.txt
@hokiedsp does this patch fix your problem ?
> Require Matlab MX_LIBRARY component

- doc/docs/NLopt_Tutorial.md
I specified the language on each relevant code example, so the proper syntax highlighting should be used.
Also I fixed the C++ part, where every angle bracket was escaped with additional quotation marks and thus hiding some relevant information in the online docs.
Also I added a C++ output functionality with `std::setprecision` (from the include `iomanip`) which behaves equivalent to the printf from the C\C++ part.
> Docs: Refined syntax highlighting and fixed c++

- src/algs/ags/ags.cc
Stop by max time was already implemented.
> Add force stop criterion for AGS

- CMakeLists.txt
> Fix THREADLOCAL definition

- CMakeLists.txt
- cmake/TargetLinkLibrariesWithDynamicLookup.cmake
- src/swig/CMakeLists.txt
> Link swig modules with dynamic lookup 

- doc/nlopt-mkdocs-theme/footer.html
> Fix footer link

- src/algs/auglag/auglag.c
> AUGLAG: Fix arithmetic exception

- cmake/FindNumPy.cmake
Now print a message when numpy is not found.
Closes #308
> CMake: Enhance numpy detection

- src/api/optimize.c
> Allow force_stop with dimension elimination

- CMakeLists.txt
> CMake: Simplify python install location

- src/algs/ags/ags.cc
- src/algs/ags/evolvent.cc
- src/algs/ags/solver.cc
- src/algs/slsqp/slsqp.c
- src/algs/stogo/stogo.cc
- src/algs/stogo/tools.cc
- src/octave/nlopt_optimize-oct.cc
Improves compatibility with ARM.  See [https://github.com/stevengj/nlopt/issues/413](https://github.com/stevengj/nlopt/issues/413)
> Remove use of long double in slsqp.c

- doc/docs/NLopt_Introduction.md
Fix link in NLopt_Introduction.md
> Fix link in NLopt_Introduction.md

- CMakeLists.txt
- nlopt.pc.in
`pkg-config` does work on Windows; this PR will have the `.pc` file installed there as well.
From https://github.com/conda-forge/nlopt-feedstock/pull/48.
> Install pkg-config file on Windows

- CMakeLists.txt
- src/algs/ags/local_optimizer.cc
- src/algs/ags/solver.cc
- src/api/nlopt-internal.h
xref https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html
also fix some warnings
> CMake: Support UNITY_BUILD

- CMakeLists.txt
- NEWS.md
NEWS and version bump
Closes #543
> prepare for 2.8 release

- src/algs/luksan/plip.c
- src/algs/luksan/plis.c
- src/algs/luksan/pnet.c
> allow negative maxeval in luksan algorithms

- src/algs/slsqp/slsqp.c
> slsqp: check p>n
