util/stop.c
hi,
I got this error introduced by 61fe516 when compiling git head with gcc:
```
make[2]: Entering directory '/home/schueller/projects/nlopt/build/util'
/bin/sh ../libtool  --tag=CC   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../util -I..  -I../../api   -g -O2 -Wall -W -Wcast-qual -Wpointer-arith -Wcast-align -Wno-long-long -pedantic -Wshadow -Wwrite-strings -Wredundant-decls -Wundef -Wconversion -MT stop.lo -MD -MP -MF .deps/stop.Tpo -c -o stop.lo ../../util/stop.c
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../util -I.. -I../../api -g -O2 -Wall -W -Wcast-qual -Wpointer-arith -Wcast-align -Wno-long-long -pedantic -Wshadow -Wwrite-strings -Wredundant-decls -Wundef -Wconversion -MT stop.lo -MD -MP -MF .deps/stop.Tpo -c ../../util/stop.c  -fPIC -DPIC -o .libs/stop.o
../../util/stop.c: …
```
=> fix conversion error in stop.c

Makefile.am, configure.ac, swig/Makefile.am
When building the C++ library, some symbols were missing because libtool didn't use the right tag.
Also the python extension wasn't linked to the python libraries.
=> add missing linking for C++

swig/Makefile.am
Prior ro this patch, I would see errors when building in parallel when the rule for nlopt.scm.in and nlopt-guild.cpp were run in parallel (actually the same rule), causing a race condition on the rename of nlopt.scm to nlopt.scm.in:
swig -I../api -outdir . -c++ -guile -scmstub -o nlopt-guile.cpp ./nlopt.i
swig -I../api -outdir . -c++ -python -o nlopt-python.cpp ./nlopt.i
swig -I../api -outdir . -c++ -guile -scmstub -o nlopt.scm.in ./nlopt.i
../api/nlopt.hpp:122: Warning 401: Nothing known about base class 'std::runtime_error'. Ignored.
../api/nlopt.hpp:127: Warning 401: Nothing known about base class 'std::runtime_error'. Ignored.
../api/nlopt.hpp:122: Warning 401: Nothing known about base class 'std::runtime_error'. Ignored.
../api/nlopt.hpp:127: Warning 401: Nothing known about base …
=> Chain build rules for guile and python bindings to avoid race conditions in parallel builds

CMakeLists.txt, api/CMakeLists.txt
The switch to CMake looks great, thank you very much. The only thing that got lost is the use of the GNUInstallDirs module from CMake to support platform-specific installation directories. This is especially noticeable for LIBDIR (possible values include 'lib', 'lib64', 'lib/x86_64-linux-gnu' depending on the target platform). It requires a minimum CMake version of 2.8.5 however.
=> Use CMake module GNUInstallDirs to support platform-specific installation directories

api/general.c
The overflow happens due to operator precedence.
re https://github.com/stevengj/nlopt/issues/127
=> Fixing Integer Overflow in nlopt_srand_time

.travis.yml, CMakeLists.txt, swig/CMakeLists.txt, test/CMakeLists.txt
This PR facilitates the inclusion of `nlopt` into other CMake projects.
- The "private" include directories are defined in a per-target basis via `target_include_directories` instead of `include_directories`. This has the advantage that it doesn't "pollute" parent projects.
- Public include directories are set via the INTERFACE argument in `target_include_directories`. To keep it simple the original header `nlopt.h` is simply copied in the `${PROJECT_BINARY_DIR}/api` folder, which is used as the interface include directory for `nlopt`. Unfortunatelly, absolute paths cannot be given as interface include directories for installed targets, hence the need for the trick with `$<BUILD_INTERFACE:...>`. However this generator expression has been introduced in cmake 3.0, so the minimum required …
=> Prefer target_include_directories in CMake build script

CMakeLists.txt
This patch fixes the DLL exports and imports for Windows. If a shared library is built, NLOPT_DLL must be defined for the library itself and everything linking against it (PUBLIC) whereas NLOPT_DLL_EXPORT must only be defined for the library itself (PRIVATE).
=> Fix dllexport and dllimport for Windows

api/options.c
=> Fix get|set lower|upper bounds methods warnings

CMakeLists.txt
This patch adds a namespace to exported CMake targets as recommended by CMake for imported targets (https://cmake.org/cmake/help/v3.9/manual/cmake-developer.7.html#a-sample-find-module).
It also adds the location of the include directory at install time to the target properties to enable target-based linking.
=> Add namespace for CMake targets and add install include directories to target properties

CMakeLists.txt
This patch installs the PDB file with debug symbols generated by MSVC into the installation's bin directory when building shared libraries and using the Debug or RelWithDebInfo configuration. This is only supported by CMake >= 3.1.
=> Install PDB file with debug information when using Visual Studio

CMakeLists.txt
Change to RELATIVE_INSTALL_INCLUDE_DIR similar to other install() variables as absolute paths are not accepted by CPack for an NSIS installer.
=> Change install destination for headers to relative path

.travis.yml, CMakeLists.txt, api/general.c, api/optimize.c, appveyor.yml, doc/docs/NLopt_Installation.md, nlopt_config.h.in, test/CMakeLists.txt
NLopt is used as a git submodule, this allows not to confuse options of the parent project.
cc @jdumas
=> Prefix cmake options

doc/docs/NLopt_Tutorial.md
On the documentation site the include header code is not shown correctly. The markdown formatting issue is fixed in this PR.
=> fix code formatting for including headers

src/algs/stogo/global.h
Having a base class without virtual destructor could result in undefined behavior (most possibly in a memory leak) when deleting an instance through a base class pointer.
Get rid of the following warnings: 
```
In file included from /home/dave/gitrepos/nlopt/src/algs/stogo/stogo.cc:5:
/home/dave/gitrepos/nlopt/src/algs/stogo/global.h:39:7: warning: 'Global' has virtual functions but
non-virtual destructor [-Wnon-virtual-dtor]
class Global: public GlobalParams {
^
/home/dave/gitrepos/nlopt/src/algs/stogo/stogo.cc:7:7: warning: 'MyGlobal' has virtual functions but
non-virtual destructor [-Wnon-virtual-dtor]
class MyGlobal : public Global {
^
```
=> Add virtual destructor to class Global (in algs/stogo/)

doc/docs/NLopt_Algorithms.md
Now formatting of references in docs is broken for AGS. This PR tries to fix that.
=> Fix wrong layout of references in docs

test/CMakeLists.txt
With nmake there is no subdir, so find the nlopt dll here too.
Set it only for windows hosts, not accurate when cross-compiling.
=> Set PATH on windows hosts only

.travis.yml, CMakeLists.txt, appveyor.yml, doc/docs/NLopt_Installation.md, nlopt.pc.in
It's silly not to provide all algorithms by default,
c++ compiler are easy to find these days, worst case it can still be disabled
Also remove lib suffix
=> Enable CXX by default

.travis.yml, src/api/f77api.c, src/api/f77funcs_.h
=> Export Fortran symbols

doc/docs/index.md
Last year I made a Rust wrapper for `nlopt`. It's pretty stable and being used in production so I thought it belonged here.
=> Docs: add Rust link

src/util/stop.c
Like `nlopt_stop_x`, the `nlopt_stop_xs` function should stop only if *all* of the variables are converged to with the given tolerance, not if *any* of them are.  Reported by @aitap in https://github.com/stevengj/nlopt/pull/183#issuecomment-437497937
(It doesn't seem like this function is used anymore, so the bug shouldn't affect anyone.  Still, it's better not to have this problem sitting in the code.)
=> make nlopt_stop_xs consistent with nlopt_stop_x

doc/docs/NLopt_Reference.md, src/api/nlopt.h, src/api/options.c
Adds `nlopt_set_lower_bound` and `nlopt_set_upper_bound` to the C API, which is helpful for JuliaOpt/NLopt.jl#130 since https://github.com/JuliaOpt/MathOptInterface.jl prefers to specify one constraint at a time, including bound constraints.
=> add functions set_*_bound(opt, i, b)

.travis.yml, src/algs/ags/local_optimizer.cc, src/algs/ags/solver.cc, src/algs/bobyqa/bobyqa.c, src/algs/cdirect/hybrid.c, src/algs/cobyla/cobyla.c, src/algs/direct/DIRect.c, src/algs/direct/DIRserial.c, src/algs/direct/DIRsubrout.c, src/algs/esch/esch.c, src/algs/luksan/plip.c, src/algs/luksan/plis.c, src/algs/luksan/pnet.c, src/algs/luksan/pssubs.c, src/algs/neldermead/sbplx.c, src/algs/newuoa/newuoa.c, src/algs/slsqp/slsqp.c, src/algs/stogo/global.h, src/api/deprecated.c, src/api/f77funcs.h, src/api/nlopt.h
- remove set but not used variables
- (void) cast unused function arguments
- create internal function duplicates for some actually
deprecated functions, for the f77 files disable
the deprecation warning completely.
- add warning flags to travis
Note: some of the maybe-unitialized warnings do not
show in gcc 7.3.0, but travis seems to use a different one.
This closes #226.
=> Add -Wall and -Wextra, fix lots of warnings

.travis.yml, appveyor.yml, src/algs/ags/ags.cc, src/algs/ags/ags.h, src/algs/bobyqa/bobyqa.c, src/algs/cdirect/hybrid.c, src/algs/direct/DIRserial.c, src/algs/direct/DIRsubrout.c, src/algs/esch/esch.c, src/algs/luksan/plip.c, src/algs/luksan/plis.c, src/algs/luksan/pnet.c, src/algs/luksan/pssubs.c, src/api/options.c, src/util/nlopt-util.h, src/util/qsort_r.c, test/testopt.c
Fixes #259, adds `-std=c89 -pedantic -Werror` to compilation flags on Travis to catch future C89 errors.
=> c89 compatibility

src/api/options.c
Similar `nlopt_get_*` functions in `options.c` always check for
`(opt && (opt->n == 0 || argument))`, requiring a valid `nlopt * opt`
and only allowing a null argument when the optimizer is "empty".
`nlopt_get_xtol_abs` seems to have been left out (13e0f277).
=> add argument checks to nlopt_get_xtol_abs

src/algs/stogo/global.cc, src/algs/stogo/global.h, src/algs/stogo/local.cc, src/algs/stogo/local.h
As mentioned in #267, these are unnecessary and clutter up the code.   (This PR doesn't change what code is actually executed, it just removes dead code.)
=> rm obsolete #ifdef NLOPT_UTIL_H in stogo code

CMakeLists.txt, doc/docs/NLopt_Installation.md, src/octave/CMakeLists.txt, test/CMakeLists.txt, test/myconstraint.m, test/myfunc.m, test/t_matlab.m
Also matlab's c++ library might be older and incompatible with the compiler's one,
so mention in the doc the possible workaround.
Added a test.
=> Set matlab extension linker language

src/algs/stogo/tools.h
When compiling the current master on Windows with Visual studio 2017 or higher with the C++17 standard, compilation errors show up due to unary_function being removed from the C++ standard from that point on.
The correction being very simple (just remove the inheritance from unary_function from C++ standard C++11), I propose here a little patch to handle this.
Tell me what you think
=> Correct compilation error with C++17 (unary functions removed)

src/algs/stogo/tools.h
Following discussion on PR #294 , here is an improvement that should work for all compilers (windows or not). Sorry about the error in the first place
=> Add usage of _MSVC_LANG for windows C++ standard check

src/octave/CMakeLists.txt
By default, the mexFunctions seems to be hidden in the newer Matlab version, this fix force the compiler to keep the symbols visible.
=> MEX library symbols visibility set to default

doc/docs/NLopt_Python_Reference.md
Vector-valued constraints section listed `opt.add_inequality_mconstraint` twice, when it looks like it meant to list both of `opt.add_inequality_mconstraint` and `opt.add_equality_mconstraint`.
=> Show `opt.add_equality_mconstraint` as an option

doc/docs/NLopt_Algorithms.md
Dembo paper was in 1983, not 1982, and I added the DOI URL too so it will be easier for others to find than it was for me.
=> Correct Dembo year

nlopt_config.h.in, src/util/nlopt-getopt.h, test/testopt.c
=> avoid linker conflicts for nlopt-getopt.c + libc with getopt

src/algs/cdirect/cdirect.c, src/algs/cdirect/hybrid.c, src/algs/crs/crs.c, src/algs/mlsl/mlsl.c, src/algs/neldermead/nldrmd.c, src/util/redblack.c, src/util/redblack.h, src/util/redblack_test.c
Collision was seen on NetBSD, ref:
http://mail-index.netbsd.org/tech-pkg/2020/10/11/msg023893.html
Fixes #360
=> Prefix builtin rb_tree symbols to avoid colliding with libc symbols

.gitattributes
With this commit, the `.gitignore` file is not included in the release tarballs. Besides the fact that a .`gitignore` file is of no use in a release tarball, including such a file makes life a bit harder for the maintainers of downstream distributions.  For instance, Debian maintains most of its package in Git repositories and need to use their own `.gitignore.` file (see [the Debian repository for the nlopt package](https://salsa.debian.org/science-team/nlopt)).
=> Avoid inclusion of .gitignore in the release tarball

cmake/FindGuile.cmake
This allows building NLopt against Guile 3.0. The [example](https://nlopt.readthedocs.io/en/latest/NLopt_Tutorial/#example-in-gnu-guile-scheme) shown in the documentation runs fine with Guile 3.0.
=> cmake/FindGuile.cmake: Allow the detection of Guile 3.0

src/algs/bobyqa/bobyqa.c, src/algs/cdirect/cdirect.c, src/algs/cdirect/hybrid.c, src/algs/cobyla/cobyla.c, src/algs/neldermead/sbplx.c, src/algs/newuoa/newuoa.c, src/algs/praxis/praxis.c, src/api/optimize.c, src/api/options.c, src/util/stop.c
As discussed in #183, it is beneficial to avoid allocating potentially
huge buffers of size `n` unless `x`-tolerance criteria are used.
This patch adds checks for `!opt->xtol_abs` and behaves as if
`xtol_abs[i] == 0 ∀i` if true.
=> do not allocate xtol_abs unless needed

src/octave/nlopt_optimize-oct.cc
This branch fixes an issue with anonymous functions in GNU Octave 6.2.0. It should be backward compatible with Octave 5.2.0.
=> Add support for octave-6.2.0

doc/docs/NLopt_Introduction.md
Dear Prof. Johnson, 
I believe SLSQP fits in the list of algorithms supporting nonlinear equality constraints, as mentioned in the doc in [Introduction/§Equality constraints](https://nlopt.readthedocs.io/en/latest/NLopt_Introduction/#equality-constraints). Is this correct?
Best,
Pierre H.
=> Update NLopt Introduction with SLSQP mention

CMakeLists.txt, nlopt_config.h.in
Apparently unused in the NLopt source code:
* `HAVE_DLFCN_H`.
* `HAVE_STRING_H`
* `HAVE_STRINGS_H`
* `HAVE_INTTYPES_H`
* `HAVE_MEMORY_H`
* `HAVE_STDLIB_H`
* `HAVE_SYS_TYPES_H`
* `HAVE_SYS_STAT_H`
=> Remove unnessary checks and defines

src/api/general.c, src/api/nlopt.h
=> Fix undefined behaviour in nlopt_result_from_string

test/t_octave.m
The output of the call to `nlopt_optimize` is verified using the `assert` function (https://github.com/rlaboiss/nlopt/commit/e3a1f29f3470bd812f09cbcbbee9b53391339fe1). This allows the detection of eventual problems when running the Octave unit test. Also, the code is made less verbose by adding semicolons to the end of the lines whose output is not informative (https://github.com/rlaboiss/nlopt/commit/8a2e87108176bddcc836f864d7230acf7109af74).
=> Improve octave test

doc/docs/index.md
👋 Hi there. I was recently integrating NLopt into a project I'm working on. Having started on the homepage (https://nlopt.readthedocs.io/en/latest/), I downloaded the suggested latest version which was 2.6.2. I later tried to use `nlopt::opt::set_param` but couldn't get it to compile, complaining that the function did not exist. It turns out that 2.6.2 is not the latest version but 2.7.1 is so I thought I could do with updating in the docs! I perhaps could have done some more digging, but the readthedocs site comes up on Google first for me.
=> Update latest version number on homepage

cmake/FindGuile.cmake
Add support for version-suffixed guile and guile-config as it's packaged
in Fedora (guile3.0, guile-config3.0 and guile2.2, guile-config2.2).
=> CMake: Fix guile detection in Fedora

src/algs/slsqp/slsqp.c
Previously, it could stop on ftol or xtol termination criteria, even if some constraints are still blatantly violated. This fixes #368.
=> Only exit SLSQP successfully if solution is feasible

CMakeLists.txt, nlopt_config.h.in, src/api/general.c, src/api/nlopt-in.hpp, src/api/optimize.c, test/CMakeLists.txt, test/cpp_functor.cxx
This PR implements a wrapper `nlopt::functor_wrapper` for C++ style functors via `std::function`, and two new overloads of `nlopt::set_min_objective`, `nlopt::set_max_objective`.
In order to allow that, a new member field in the `myfunc_data` struct is added: `functor_type functor;`, where `functor_type` is defined as
```c++
typedef std::function<double(unsigned, const double*, double*)> functor_type;
```
This is not introduced as a pointer (like the other function-pointers are) because `std::function` is already a container that stores a pointer, and abstracts it away.
**Important:** note that the signature for the functor does not include `void* data` unlike all other function-pointers. That is because it is assumed that the functor already has all the data it needs.
This PR allows now …
=> Implement C++ style functors as targets for objectives

src/api/optimize.c
=> fix forced_stop for empty dims

doc/docs/NLopt_Reference.md, src/api/options.c
=> options: nlopt_set_xtol_abs check xtol_abs

src/api/options.c
Hi,
I have noticed that when the number of equality constraints exceeds the number of variables, NLOPT refuses to add them. However, this does not necessarily mean that there is no solution as there can be redundancy in the constraints that may be non-trivial to remove for the non-linear situation from the user side. Moreover, even if the number of equality constraints is less than the number of variables, this check cannot guarantee the solution's existence.  So this check seems not to make a lot of sense.
Therefore, I removed the check in this PR, or do you prefer a CMake option and preprocess directive that can conditionally disable it?
=> Remove equality constriant number check when adding constraint

src/algs/stogo/stogo.cc
BTW I saw that in `src/algs/ags/solver.cc` all of the code inside the anonymous was indented by an extra level.  Let me know if you'd like me to reformat this patch in the same way.
=> Use the anonymous namespace for a file-local class in stogo

doc/docs/NLopt_C-plus-plus_Reference.md
Fixed a typo in the header include statement. Previously the name of the header was hidden because of incorrect markdown syntax.
=> Fix include statement

src/api/general.c
Fixes issues introduced in #457
There where missing commas at the end of `"AGS (global, no-derivative)"` causing it to be merged with the next string.
It's ordering was also changed without considering that the order of the items in the array mattered.
This PR fixes the ordering and makes sure that there are terminating commas for each entry.
=> Fix nlopt_algorithm_name

doc/docs/NLopt_Reference.md
The current documentation shows two times the same function. So, I guess this is what it probably meant by the original author.
=> Fix small copy paste bug in NLopt_Reference.md

src/algs/ags/solver.cc, src/algs/stogo/linalg.cc, src/algs/stogo/linalg.h, src/algs/stogo/tools.h
Including `<iostream>` means introducing the static (global) constructors and destructors for `std::cin`, `std::cerr`, and `std::cout`. That extra init and fini code is undesirable when those streams are not actually used.
(See https://en.cppreference.com/w/cpp/io/ios_base/Init for details.)
=> Remove unncessary <iostream> includes

doc/docs/NLopt_C-plus-plus_Reference.md, doc/docs/NLopt_Guile_Reference.md, doc/docs/NLopt_Java_Reference.md, doc/docs/NLopt_Python_Reference.md, src/api/nlopt-in.hpp, test/CMakeLists.txt, test/t_except.cxx
Call opt.set_exceptions_enabled(false) before opt.optimize to avoid throwing an exception. The caller is then responsible for checking the returned result or opt.last_result(). The advantage is that, for the SWIG-friendly overload, the returned best point (which can be quite good in, e.g., the roundoff_limited case) is not lost (but then the caller MUST check opt.last_result() to know whether anything has gone wrong). The default is exceptions_enabled=true, so by default, nothing changes.
src/api/nlopt-in.hpp (opt::exceptions_enabled): New private member variable.
(opt::opt (all overloads)): Initialize it (default it to true, copy it in the copy constructor).
(opt::operator=): Copy it.
(opt::optimize): Only call mythrow if exceptions_enabled. (get_exceptions_enabled): New public inline …
=> C++: Allow disabling exceptions in opt::optimize.

CMakeLists.txt, NEWS.md
Bump versions for 2.10.
@jschueller, any reason why we shouldn't release this now (because of #584)?
=> release 2.10

src/algs/slsqp/slsqp.c
src/algs/slsqp/slsqp.c (src/algs/slsqp/slsqp.c): Fix the check for more equality constraints than variables (introduced by PR #593 to fix #592) so that vector constraints (mconstraints) are correctly counted: the count to consider here is ptot (the total number of scalar equality constraints), not p (the number of equality constraints that may be vector constraints).
=> slsqp: check ptot>n, not p>n (proper fix for #592)

test/CMakeLists.txt
There is an off-by-one error in the `test/CMakeLists.txt` that causes the tests to attempt to run disabled Luksan solver code, which in turn causes the test suite to fail:
```
Optimizing Rosenbrock function (2 dims) using Preconditioned truncated Newton with restarting (local, derivative-based) algorithm
lower bounds at lb = [ -2 -2]
upper bounds at ub = [ 2 2]
Starting guess x = [ 0.629447 0.811584]
Starting function value = 17.3914
ERROR - attempting to use NLOPT_LD_TNEWTON*, but Luksan code disabled
finished after 1.4e-05 seconds.
return code -2 from nlopt_minimize
Start 59: testopt_algo19_obj1
52/77 Test #57: testopt_algo18_obj1 ..............***Failed    0.01 sec
testopt: error in nlopt_minimize
-----------------------------------------------------------
Optimizing McCormic function …
```
=> nlopt: fix tests failing when luksan solvers are disabled
